// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjPmNF05H4mRI-ZrCFP_GPm5DnMKSTfLU',
    appId: '1:253400070757:web:a66026b13bb258d5b3648c',
    messagingSenderId: '253400070757',
    projectId: 'skindisease-a5647',
    authDomain: 'skindisease-a5647.firebaseapp.com',
    storageBucket: 'skindisease-a5647.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJwdAZolXmaHOtm5tkw15kHkWitj4SuyI',
    appId: '1:253400070757:android:bbe3bb68d3bca1e5b3648c',
    messagingSenderId: '253400070757',
    projectId: 'skindisease-a5647',
    storageBucket: 'skindisease-a5647.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-qDSb8EOGk5PtxZ8NYPZzZcYTUHe5guQ',
    appId: '1:253400070757:ios:a0adcfffba5f6013b3648c',
    messagingSenderId: '253400070757',
    projectId: 'skindisease-a5647',
    storageBucket: 'skindisease-a5647.firebasestorage.app',
    iosBundleId: 'com.example.skinDisease1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-qDSb8EOGk5PtxZ8NYPZzZcYTUHe5guQ',
    appId: '1:253400070757:ios:a0adcfffba5f6013b3648c',
    messagingSenderId: '253400070757',
    projectId: 'skindisease-a5647',
    storageBucket: 'skindisease-a5647.firebasestorage.app',
    iosBundleId: 'com.example.skinDisease1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjPmNF05H4mRI-ZrCFP_GPm5DnMKSTfLU',
    appId: '1:253400070757:web:11f71fb644d65fb3b3648c',
    messagingSenderId: '253400070757',
    projectId: 'skindisease-a5647',
    authDomain: 'skindisease-a5647.firebaseapp.com',
    storageBucket: 'skindisease-a5647.firebasestorage.app',
  );

}